yaml
---
version: '3.8'

services:
web:
  build:
    context: ..
    dockerfile: docker/Dockerfile
  ports:
    - "8000:8000"
  depends_on:
    - db
    - redis
  environment:
    - DATABASE_URL=postgresql://user:password@db:5432/transactions_db
    - REDIS_URL=redis://redis:6379
  volumes:
    - ../:/app
  networks:
    - app-network

db:
  image: postgres:14
  environment:
    - POSTGRES_USER=user
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=transactions_db
  ports:
    - "5432:5432"
  volumes:
    - postgres_data:/var/lib/postgresql/data
  networks:
    - app-network

redis:
  image: redis:7
  ports:
    - "6379:6379"
  volumes:
    - redis_data:/data
  networks:
    - app-network

volumes:
postgres_data:
redis_data:

networks:
app-network:
  driver: bridge